name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Test
      run: deno test denops/surround/
